language: java
jdk: openjdk11
cache:
  directories:
    - $HOME/.m2

script:
  - mvn --settings .travis/settings.xml -P poms -U help:active-profiles clean install:install
  - mvn --settings .travis/settings.xml -P jars -U help:active-profiles clean install:install
