name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Maven Repository Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Deploy TOP POM
        env:
          AVN_REPO_USERNAME: ${{ secrets.AVN_REPO_USERNAME }}
          AVN_REPO_PASSWORD: ${{ secrets.AVN_REPO_PASSWORD }}
        run: mvn --settings .github/settings.xml -B -P top -U help:active-profiles clean deploy:deploy

      - name: Deploy POMS
        env:
          AVN_REPO_USERNAME: ${{ secrets.AVN_REPO_USERNAME }}
          AVN_REPO_PASSWORD: ${{ secrets.AVN_REPO_PASSWORD }}
        run: mvn --settings .github/settings.xml -B -P poms -U help:active-profiles clean deploy:deploy

      - name: Deploy JARS
        env:
          AVN_REPO_USERNAME: ${{ secrets.AVN_REPO_USERNAME }}
          AVN_REPO_PASSWORD: ${{ secrets.AVN_REPO_PASSWORD }}
        run: mvn --settings .github/settings.xml -B -P asms -U help:active-profiles clean deploy
