name: Avereon Maven CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Deploy POMS
        run: mvn --settings .travis/settings.xml -B -P poms -U help:active-profiles clean deploy:deploy
      - name: Deploy JARS
        run: mvn --settings .travis/settings.xml -B -P jars -U help:active-profiles clean deploy
